package resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit/middleware"
)

// AccountListHandlerFunc turns a function with the right signature into a account list handler
type AccountListHandlerFunc func() middleware.Responder

// Handle executing the request and returning a response
func (fn AccountListHandlerFunc) Handle() middleware.Responder {
	return fn()
}

// AccountListHandler interface for that can handle valid account list params
type AccountListHandler interface {
	Handle() middleware.Responder
}

// NewAccountList creates a new http.Handler for the account list operation
func NewAccountList(ctx *middleware.Context, handler AccountListHandler) *AccountList {
	return &AccountList{Context: ctx, Handler: handler}
}

/*AccountList swagger:route GET /account resource accountList

returns the account list

*/
type AccountList struct {
	Context *middleware.Context
	Handler AccountListHandler
}

func (o *AccountList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)

	if err := o.Context.BindValidRequest(r, route, nil); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle() // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
