package resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"github.com/loofort/softswiss/models"
)

/*AccountItemOK show account info

swagger:response accountItemOK
*/
type AccountItemOK struct {

	// In: body
	Payload *models.Account `json:"body,omitempty"`
}

// NewAccountItemOK creates AccountItemOK with default headers values
func NewAccountItemOK() *AccountItemOK {
	return &AccountItemOK{}
}

// WithPayload adds the payload to the account item o k response
func (o *AccountItemOK) WithPayload(payload *models.Account) *AccountItemOK {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *AccountItemOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*AccountItemNotFound account not found info

swagger:response accountItemNotFound
*/
type AccountItemNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewAccountItemNotFound creates AccountItemNotFound with default headers values
func NewAccountItemNotFound() *AccountItemNotFound {
	return &AccountItemNotFound{}
}

// WithPayload adds the payload to the account item not found response
func (o *AccountItemNotFound) WithPayload(payload *models.Error) *AccountItemNotFound {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *AccountItemNotFound) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*AccountItemDefault unexpected error

swagger:response accountItemDefault
*/
type AccountItemDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewAccountItemDefault creates AccountItemDefault with default headers values
func NewAccountItemDefault(code int) *AccountItemDefault {
	if code <= 0 {
		code = 500
	}

	return &AccountItemDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the account item default response
func (o *AccountItemDefault) WithStatusCode(code int) *AccountItemDefault {
	o._statusCode = code
	return o
}

// WithPayload adds the payload to the account item default response
func (o *AccountItemDefault) WithPayload(payload *models.Error) *AccountItemDefault {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *AccountItemDefault) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
