package command

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"github.com/loofort/softswiss/models"
)

/*DepositOK return account info with total money amount

swagger:response depositOK
*/
type DepositOK struct {

	// In: body
	Payload *models.Account `json:"body,omitempty"`
}

// NewDepositOK creates DepositOK with default headers values
func NewDepositOK() *DepositOK {
	return &DepositOK{}
}

// WithPayload adds the payload to the deposit o k response
func (o *DepositOK) WithPayload(payload *models.Account) *DepositOK {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *DepositOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DepositNotFound account not found info

swagger:response depositNotFound
*/
type DepositNotFound struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewDepositNotFound creates DepositNotFound with default headers values
func NewDepositNotFound() *DepositNotFound {
	return &DepositNotFound{}
}

// WithPayload adds the payload to the deposit not found response
func (o *DepositNotFound) WithPayload(payload *models.Error) *DepositNotFound {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *DepositNotFound) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DepositDefault unexpected error

swagger:response depositDefault
*/
type DepositDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewDepositDefault creates DepositDefault with default headers values
func NewDepositDefault(code int) *DepositDefault {
	if code <= 0 {
		code = 500
	}

	return &DepositDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the deposit default response
func (o *DepositDefault) WithStatusCode(code int) *DepositDefault {
	o._statusCode = code
	return o
}

// WithPayload adds the payload to the deposit default response
func (o *DepositDefault) WithPayload(payload *models.Error) *DepositDefault {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *DepositDefault) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
