package command

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"github.com/loofort/softswiss/models"
)

/*WithdrawOK Ok

swagger:response withdrawOK
*/
type WithdrawOK struct {

	// In: body
	Payload *models.Account `json:"body,omitempty"`
}

// NewWithdrawOK creates WithdrawOK with default headers values
func NewWithdrawOK() *WithdrawOK {
	return &WithdrawOK{}
}

// WithPayload adds the payload to the withdraw o k response
func (o *WithdrawOK) WithPayload(payload *models.Account) *WithdrawOK {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *WithdrawOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*WithdrawDefault withdraw default

swagger:response withdrawDefault
*/
type WithdrawDefault struct {
	_statusCode int
}

// NewWithdrawDefault creates WithdrawDefault with default headers values
func NewWithdrawDefault(code int) *WithdrawDefault {
	if code <= 0 {
		code = 500
	}

	return &WithdrawDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the withdraw default response
func (o *WithdrawDefault) WithStatusCode(code int) *WithdrawDefault {
	o._statusCode = code
	return o
}

// WriteResponse to the client
func (o *WithdrawDefault) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(o._statusCode)
}
